const Router = require("express")
const router = new Router()
const autoPartRoutes = require('./autoPartRoutes')
const tiersRoutes = require('./tiersRoutes')
const favouriteAllRoutes = require('./favouriteAllRoutes')
const favouriteRoutes = require('./favouriteRoutes')
const feedbackRoutes = require('./feedbackRoutes')
const historyAllRoutes = require('./historyAllRoutes')
const historyRoutes = require('./historyRoutes')
const orderDataRoutes = require('./orderDataRoutes')
const ordersRoutes = require('./ordersRoutes')
const typeRoutes = require('./typeRoutes')
const basketRoutes = require('./basketRoutes')
const basketAllRoutes = require('./basketAllRoutes')
const connectRoutes = require('./connectRoutes')
const deliveryRoutes = require('./deliveryRoutes')
const userRoutes = require('./userRoutes')


router.use('/user', userRoutes)
router.use('/type', typeRoutes)
router.use('/autoPart', autoPartRoutes)
router.use('/basketAll', basketAllRoutes)
router.use('/connect', connectRoutes)
router.use('/history', historyRoutes)
router.use('/historyAll', historyAllRoutes)
router.use('/basket', basketRoutes)
router.use('/tiers', tiersRoutes)
router.use('/orders', ordersRoutes)
router.use('/orderData', orderDataRoutes)
router.use('/feedback', feedbackRoutes)
router.use('/favourite', favouriteRoutes)
router.use('/favouriteAll', favouriteAllRoutes)
router.use('/delivery', deliveryRoutes)

module.exports = router